.TH "Содержание директории C:/Users/pagan/source/repos/TPOAS3_1/TPOAS3_1" 3 "Вт 17 Май 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/pagan/source/repos/TPOAS3_1/TPOAS3_1
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBTPOAS3_1\&.cpp\fP"
.br
.in -1c
