.TH "C:/Users/pagan/source/repos/TPOAS3_1/TPOAS3_1/TPOAS3_1.cpp" 3 "Вт 17 Май 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/pagan/source/repos/TPOAS3_1/TPOAS3_1/TPOAS3_1.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Структуры данных"

.in +1c
.ti -1c
.RI "class \fBpom\fP"
.br
.RI "Основной класс "
.ti -1c
.RI "class \fBagen\fP"
.br
.RI "Вспомогательный класс "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
