.TH "pom" 3 "Tue May 17 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pom \- Основной класс  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay\fP ()"
.br
.RI "Функция выводит в консоль стоимость квадратного метра и площадь помещения "
.ti -1c
.RI "void \fBinit\fP (double c1, int a1)"
.br
.RI "Эта функция присваивает начальное значение для стоимости квадратного метра помещения и его площади "
.ti -1c
.RI "double \fBp\fP ()"
.br
.RI "Стоимость помещения "
.in -1c
.SH "Detailed Description"
.PP 
Основной класс 

В нём находится метод, вычисляющий стоимость помещения 
.SH "Member Function Documentation"
.PP 
.SS "void pom::init (double с1, int a1)"

.PP
Эта функция присваивает начальное значение для стоимости квадратного метра помещения и его площади 
.PP
\fBParameters\fP
.RS 4
\fIc1\fP входящий параметр стоимости квадратного метра 
.br
\fIk1\fP входящий параметр площади помещения 
.RE
.PP

.SS "double pom::p ()"

.PP
Стоимость помещения Функция возвражает произведение стоимости квадратного метра и площади помещения 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
