.TH "C:/Users/Admin/Desktop/QA3/ConsoleApplication1/ConsoleApplication1 Directory Reference" 3 "Tue Sep 20 2022" "Version 1.1" "QA3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Admin/Desktop/QA3/ConsoleApplication1/ConsoleApplication1 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConsoleApplication1\&.cpp\fP"
.br
.in -1c
