.TH "C:/Users/Admin/Desktop/QA3/ConsoleApplication1/ConsoleApplication1/ConsoleApplication1.cpp" 3 "Tue Sep 20 2022" "Version 1.1" "QA3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Admin/Desktop/QA3/ConsoleApplication1/ConsoleApplication1/ConsoleApplication1.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclothes\fP"
.br
.RI "Вспомогательный класс Одежда "
.ti -1c
.RI "class \fBClothes_ratio\fP"
.br
.RI "Производный класс Коэффициент мастерства пошива одежды "
.ti -1c
.RI "class \fBatelier\fP"
.br
.RI "Основной класс: Ателье "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for QA3 from the source code\&.
