.TH "film" 3 "Tue May 17 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
film
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFL\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (int cost1, int gain1)"
.br
.ti -1c
.RI "void \fBDisplay\fP ()"
.br
.ti -1c
.RI "void \fBRead\fP ()"
.br
.ti -1c
.RI "float \fBokup_f\fP ()"
.br
.ti -1c
.RI "double \fBGetGain\fP ()"
.br
.ti -1c
.RI "double \fBGetCost\fP ()"
.br
.ti -1c
.RI "int \fBsumm\fP (\fBfilm\fP X)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBcost\fP"
.br
.ti -1c
.RI "int \fBgain\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
