.TH "film_studio" 3 "Tue May 17 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
film_studio
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDisplay\fP ()"
.br
.ti -1c
.RI "void \fBRead\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP (char *n, int cost1, int gain1, int cost2, int gain2, int cost3, int gain3, int first_income1, int two_income2, int third_income3)"
.br
.ti -1c
.RI "double \fBsumm_d\fP ()"
.br
.ti -1c
.RI "\fBfilm\fP \fBbest_f\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
